Name:           ros-kinetic-naoqi-sensors-py
Version:        0.5.5
Release:        0%{?dist}
Summary:        ROS naoqi_sensors_py package

Group:          Development/Libraries
License:        LGPL and Apache2
URL:            http://ros.org/wiki/naoqi_sensors
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-kinetic-camera-info-manager
Requires:       ros-kinetic-camera-info-manager-py
Requires:       ros-kinetic-dynamic-reconfigure
Requires:       ros-kinetic-naoqi-driver-py
Requires:       ros-kinetic-octomap
Requires:       ros-kinetic-rospy
Requires:       ros-kinetic-sensor-msgs
BuildRequires:  boost-devel
BuildRequires:  ros-kinetic-camera-info-manager
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-dynamic-reconfigure
BuildRequires:  ros-kinetic-naoqi-driver-py
BuildRequires:  ros-kinetic-octomap
BuildRequires:  ros-kinetic-octomap-msgs
Conflicts:      ros-kinetic-nao-sensors

%description
ROS driver for miscellaneous sensors on NAO. Python bindings for camera, sonar
and octomap C++: bindings for camera only (requires NAOqi to build)

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Sep 19 2016 Séverin Lemaignan <severin.lemaignan@epfl.ch> - 0.5.5-0
- Autogenerated by Bloom

* Fri May 20 2016 Séverin Lemaignan <severin.lemaignan@epfl.ch> - 0.5.4-0
- Autogenerated by Bloom

