Name:           ros-jade-naoqi-sensors
Version:        0.4.7
Release:        0%{?dist}
Summary:        ROS naoqi_sensors package

Group:          Development/Libraries
License:        LGPL and Apache2
URL:            http://ros.org/wiki/naoqi_sensors
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-jade-camera-info-manager
Requires:       ros-jade-camera-info-manager-py
Requires:       ros-jade-diagnostic-updater
Requires:       ros-jade-dynamic-reconfigure
Requires:       ros-jade-image-transport
Requires:       ros-jade-naoqi-driver
Requires:       ros-jade-nodelet
Requires:       ros-jade-octomap
Requires:       ros-jade-roscpp
Requires:       ros-jade-rospy
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-tf
BuildRequires:  boost-devel
BuildRequires:  ros-jade-camera-info-manager
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-diagnostic-updater
BuildRequires:  ros-jade-driver-base
BuildRequires:  ros-jade-dynamic-reconfigure
BuildRequires:  ros-jade-image-transport
BuildRequires:  ros-jade-naoqi-driver
BuildRequires:  ros-jade-nodelet
BuildRequires:  ros-jade-octomap
BuildRequires:  ros-jade-octomap-msgs
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-tf
Conflicts:      ros-jade-nao-sensors

%description
ROS driver for miscellaneous sensors on NAO. Python bindings for camera, sonar
and octomap C++: bindings for camera only (requires NAOqi to build)

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Fri May 01 2015 Séverin Lemaignan <severin.lemaignan@epfl.ch> - 0.4.7-0
- Autogenerated by Bloom

