Name:           ros-indigo-naoqi-bridge
Version:        0.4.7
Release:        0%{?dist}
Summary:        ROS naoqi_bridge package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/nao
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-naoqi-driver
Requires:       ros-indigo-naoqi-msgs
Requires:       ros-indigo-naoqi-sensors
BuildRequires:  ros-indigo-catkin

%description
Meta package to interface ROS with Aldebaran's NAOqi.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Mar 30 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.7-0
- Autogenerated by Bloom

* Fri Feb 27 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.6-0
- Autogenerated by Bloom

* Wed Feb 11 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.5-0
- Autogenerated by Bloom

* Fri Jan 16 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.4-0
- Autogenerated by Bloom

* Sun Dec 14 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.3-1
- Autogenerated by Bloom

* Sun Dec 14 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.3-0
- Autogenerated by Bloom

* Wed Nov 26 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.4.2-0
- Autogenerated by Bloom

