Name:           ros-indigo-naoqi-sensors-py
Version:        0.5.3
Release:        0%{?dist}
Summary:        ROS naoqi_sensors_py package

Group:          Development/Libraries
License:        LGPL and Apache2
URL:            http://ros.org/wiki/naoqi_sensors
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-indigo-camera-info-manager
Requires:       ros-indigo-camera-info-manager-py
Requires:       ros-indigo-dynamic-reconfigure
Requires:       ros-indigo-naoqi-driver-py
Requires:       ros-indigo-octomap
Requires:       ros-indigo-rospy
Requires:       ros-indigo-sensor-msgs
BuildRequires:  boost-devel
BuildRequires:  ros-indigo-camera-info-manager
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-driver-base
BuildRequires:  ros-indigo-dynamic-reconfigure
BuildRequires:  ros-indigo-naoqi-driver-py
BuildRequires:  ros-indigo-octomap
BuildRequires:  ros-indigo-octomap-msgs
Conflicts:      ros-indigo-nao-sensors

%description
ROS driver for miscellaneous sensors on NAO. Python bindings for camera, sonar
and octomap C++: bindings for camera only (requires NAOqi to build)

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Aug 26 2015 Séverin Lemaignan <severin.lemaignan@epfl.ch> - 0.5.3-0
- Autogenerated by Bloom

* Tue Aug 11 2015 Séverin Lemaignan <severin.lemaignan@epfl.ch> - 0.5.2-0
- Autogenerated by Bloom

* Fri Jul 31 2015 Séverin Lemaignan <severin.lemaignan@epfl.ch> - 0.5.1-0
- Autogenerated by Bloom

* Thu Jul 30 2015 Séverin Lemaignan <severin.lemaignan@epfl.ch> - 0.5.0-0
- Autogenerated by Bloom

